In [1]:
import tensorflow as tf
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]


In [2]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]


In [3]:
X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])
W = tf.Variable(tf.random_normal([3,3]),name = 'weight')
b = tf.Variable(tf.random_normal([3]))

In [4]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)


In [5]:
# Correct prediction Test Model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

In [6]:
# lauch graph
with tf.Session() as sess:
    # initialize Tensorflow variable 
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],feed_dict = {X:x_data, Y:y_data})
        print(step, cost_val, W_val)
        
    #predict
    print("Prediction: ",sess.run(prediction, feed_dict={X:x_test}))
    # Caluate the accuray 
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 9.78818 [[ 1.68658566 -0.83738828 -1.36872697]
 [-2.0339272   0.12593271  0.28144395]
 [-2.0707109   1.00417519 -1.47087133]]
1 9.57924 [[ 1.68906462 -0.84344095 -1.36515331]
 [-2.01771927  0.10009567  0.29107308]
 [-2.05448198  0.9793911  -1.46231616]]
2 9.37092 [[ 1.69154084 -0.8494696  -1.36160088]
 [-2.00151682  0.0743105   0.3006559 ]
 [-2.03825593  0.95463496 -1.45378613]]
3 9.16326 [[ 1.69401407 -0.85547179 -1.35807192]
 [-1.98532069  0.04858305  0.31018719]
 [-2.02203298  0.92991018 -1.44528425]]
4 8.95636 [[ 1.69648385 -0.86144471 -1.35456872]
 [-1.96913135  0.02291971  0.31966123]
 [-2.00581336  0.90522039 -1.43681395]]
5 8.75028 [[ 1.69894993 -0.86738551 -1.35109389]
 [-1.95294952 -0.00267257  0.32907173]
 [-1.98959768  0.8805697  -1.42837906]]
6 8.54512 [[ 1.70141184 -0.87329113 -1.34765017]
 [-1.93677604 -0.02818623  0.3384119 ]
 [-1.97338617  0.85596263 -1.41998363]]
7 8.34097 [[ 1.70386934 -0.87915832 -1.34424043]
 [-1.92061162 -0.05361309  0.34767431]
 [-1.95717919  0

101 1.59012 [[ 1.77146006 -1.06036294 -1.23062634]
 [-0.89761573 -0.88149506  0.15256065]
 [-0.91964573 -0.11315015 -1.50461125]]
102 1.58845 [[ 1.76946557 -1.06007445 -1.22892034]
 [-0.8966493  -0.88141441  0.15151359]
 [-0.91903448 -0.11345388 -1.50491881]]
103 1.5868 [[ 1.76746404 -1.05978417 -1.22720909]
 [-0.89572442 -0.88132668  0.15050097]
 [-0.91846371 -0.11374737 -1.50519609]]
104 1.58516 [[ 1.76545644 -1.05949235 -1.22549331]
 [-0.8948366  -0.88123316  0.14951968]
 [-0.91792899 -0.11403239 -1.50544584]]
105 1.58354 [[ 1.76344359 -1.05919933 -1.22377348]
 [-0.89398193 -0.88113499  0.14856686]
 [-0.91742629 -0.11431048 -1.50567043]]
106 1.58192 [[ 1.76142621 -1.05890548 -1.22205007]
 [-0.89315683 -0.88103312  0.1476399 ]
 [-0.91695201 -0.11458293 -1.50587225]]
107 1.5803 [[ 1.75940502 -1.05861092 -1.22032344]
 [-0.89235812 -0.88092834  0.14673644]
 [-0.91650301 -0.11485085 -1.50605333]]
108 1.5787 [[ 1.7573806  -1.05831587 -1.21859407]
 [-0.89158303 -0.88082129  0.14585432]
 [-

InvalidArgumentError: Incompatible shapes: [3] vs. [8]
	 [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](ArgMax, ArgMax_1)]]

Caused by op 'Equal', defined at:
  File "F:\Users\Alec_zhang13\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-199a73d66435>", line 3, in <module>
    is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 681, in equal
    result = _op_def_lib.apply_op("Equal", x=x, y=y, name=name)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "F:\Users\Alec_zhang13\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [3] vs. [8]
	 [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](ArgMax, ArgMax_1)]]
