In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

In [2]:
defc(data):
    numerator = data - np.min(data, 0)#找到最小的那一行然后每行都减去这行
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [3]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]


In [4]:
# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)

[[ 0.9999999   0.9999999   0.          0.9999999   0.9999999 ]
 [ 0.70548484  0.70439545  0.9999999   0.71881775  0.83755783]
 [ 0.54412544  0.50274819  0.5760869   0.60646794  0.66063303]
 [ 0.33890349  0.3136802   0.10869564  0.4598913   0.43800914]
 [ 0.51435995  0.42582385  0.3043478   0.585048    0.42624397]
 [ 0.49556174  0.42582385  0.31521736  0.48131129  0.49276132]
 [ 0.11436063  0.          0.20652172  0.22007774  0.18597236]
 [ 0.          0.07747099  0.53260864  0.          0.        ]]


In [5]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.152309 
Prediction:
 [[ 1.634619  ]
 [ 0.06613699]
 [ 0.35008183]
 [ 0.67072517]
 [ 0.6113075 ]
 [ 0.61464411]
 [ 0.2317197 ]
 [-0.13728359]]
1 Cost:  0.152309 
Prediction:
 [[ 1.63461781]
 [ 0.06613842]
 [ 0.35008252]
 [ 0.67072499]
 [ 0.61130762]
 [ 0.61464429]
 [ 0.23172003]
 [-0.13728234]]
2 Cost:  0.152308 
Prediction:
 [[ 1.63461661]
 [ 0.06613985]
 [ 0.35008317]
 [ 0.67072481]
 [ 0.61130768]
 [ 0.61464447]
 [ 0.23172033]
 [-0.13728115]]
3 Cost:  0.152308 
Prediction:
 [[ 1.63461554]
 [ 0.06614131]
 [ 0.35008386]
 [ 0.67072463]
 [ 0.61130774]
 [ 0.61464459]
 [ 0.23172066]
 [-0.13728002]]
4 Cost:  0.152307 
Prediction:
 [[ 1.63461435]
 [ 0.0661428 ]
 [ 0.35008451]
 [ 0.67072439]
 [ 0.61130786]
 [ 0.61464477]
 [ 0.23172098]
 [-0.13727883]]
5 Cost:  0.152306 
Prediction:
 [[ 1.63461316]
 [ 0.06614426]
 [ 0.35008514]
 [ 0.67072421]
 [ 0.61130792]
 [ 0.61464494]
 [ 0.2317213 ]
 [-0.13727757]]
6 Cost:  0.152306 
Prediction:
 [[ 1.63461208]
 [ 0.06614569]
 [ 0.35008579]
 [ 0.