In [1]:
import tensorflow as tf
import numpy as np

In [7]:
xy = np.loadtxt("data-01-test-score.csv",delimiter=",",dtype=np.float32)

In [8]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [9]:
# make sure the shape and data is ok 

In [11]:
print(x_data.shape)
print("\n")
print(y_data.shape)


(25, 3)


(25, 1)


In [16]:
# make the placeholder for the tensor will be always use
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name ="weight")
b = tf.Variable(tf.random_normal([1]),name = 'baise')

# hypothesis 
hypothesis = tf.matmul(X,W)+b

In [17]:
# cost function
cost = tf.reduce_mean(tf.square(hypothesis-Y))


In [20]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [21]:
# set session for the graph
sess = tf.Session()
# initilize the global variable
sess.run(tf.global_variables_initializer())


In [22]:
for step in range(20001):
    cost_val,hy_val,_ = sess.run([cost,hypothesis,train],feed_dict={X:x_data
                                ,Y:y_data})
    if step % 10 ==0:
        print(step,"cost: ",cost_val,"\n hypothesis: \n",hy_val)

0 cost:  25574.9 
 hypothesis: 
 [[-0.9792552 ]
 [ 9.19142342]
 [ 3.95963526]
 [ 3.81095362]
 [ 9.54699898]
 [ 6.57559919]
 [-1.49976492]
 [-7.29318476]
 [ 9.91213417]
 [ 8.38508987]
 [ 2.15122843]
 [ 6.2122407 ]
 [ 5.0544095 ]
 [ 5.51377726]
 [-0.08875227]
 [ 7.77818155]
 [ 9.07876015]
 [-4.11865759]
 [ 3.29936457]
 [ 1.52652979]
 [ 0.28084421]
 [ 7.17612314]
 [-0.47544432]
 [ 1.03049707]
 [ 8.37469101]]
10 cost:  38.4912 
 hypothesis: 
 [[ 148.24502563]
 [ 188.5255127 ]
 [ 180.6701355 ]
 [ 196.26786804]
 [ 146.30877686]
 [ 107.41110992]
 [ 142.57513428]
 [  99.53556061]
 [ 177.51512146]
 [ 163.63725281]
 [ 140.94810486]
 [ 143.06240845]
 [ 187.61447144]
 [ 157.26498413]
 [ 144.64608765]
 [ 189.76745605]
 [ 153.58869934]
 [ 168.79353333]
 [ 177.34637451]
 [ 157.2603302 ]
 [ 169.22663879]
 [ 175.42247009]
 [ 160.60107422]
 [ 151.46972656]
 [ 194.23408508]]
20 cost:  37.1122 
 hypothesis: 
 [[ 149.28291321]
 [ 189.75299072]
 [ 181.88937378]
 [ 197.60165405]
 [ 147.23509216]
 [ 108.10087

350 cost:  32.2684 
 hypothesis: 
 [[ 149.51374817]
 [ 189.39268494]
 [ 181.84771729]
 [ 197.74203491]
 [ 146.64859009]
 [ 107.88091278]
 [ 144.14865112]
 [ 101.37857819]
 [ 178.40740967]
 [ 164.82896423]
 [ 142.07104492]
 [ 143.95304871]
 [ 188.62205505]
 [ 157.78285217]
 [ 146.14982605]
 [ 190.89131165]
 [ 153.64447021]
 [ 170.95567322]
 [ 178.37773132]
 [ 158.28927612]
 [ 170.90904236]
 [ 176.46580505]
 [ 162.20611572]
 [ 152.26887512]
 [ 195.14505005]]
360 cost:  32.1341 
 hypothesis: 
 [[ 149.52037048]
 [ 189.38194275]
 [ 181.84634399]
 [ 197.74584961]
 [ 146.63134766]
 [ 107.87424469]
 [ 144.16470337]
 [ 101.40948486]
 [ 178.39953613]
 [ 164.83180237]
 [ 142.07545471]
 [ 143.95120239]
 [ 188.61477661]
 [ 157.7678833 ]
 [ 146.16375732]
 [ 190.88720703]
 [ 153.61791992]
 [ 170.98265076]
 [ 178.37283325]
 [ 158.28788757]
 [ 170.92327881]
 [ 176.46214294]
 [ 162.21974182]
 [ 152.26217651]
 [ 195.13427734]]
370 cost:  32.0006 
 hypothesis: 
 [[ 149.52697754]
 [ 189.37120056]
 [ 181.84

720 cost:  27.7339 
 hypothesis: 
 [[ 149.75204468]
 [ 189.01026917]
 [ 181.80021667]
 [ 197.8770752 ]
 [ 146.03662109]
 [ 107.64012909]
 [ 144.71559143]
 [ 102.46990204]
 [ 178.12329102]
 [ 164.91918945]
 [ 142.22592163]
 [ 143.88238525]
 [ 188.3687439 ]
 [ 157.25878906]
 [ 146.64019775]
 [ 190.74346924]
 [ 152.71043396]
 [ 171.90931702]
 [ 178.2094574 ]
 [ 158.24516296]
 [ 171.4112854 ]
 [ 176.33276367]
 [ 162.68823242]
 [ 152.0403595 ]
 [ 194.76495361]]
730 cost:  27.6229 
 hypothesis: 
 [[ 149.75827026]
 [ 189.00035095]
 [ 181.79902649]
 [ 197.88052368]
 [ 146.02081299]
 [ 107.63378143]
 [ 144.73016357]
 [ 102.49794769]
 [ 178.11579895]
 [ 164.92121887]
 [ 142.2298584 ]
 [ 143.88041687]
 [ 188.36230469]
 [ 157.2454071 ]
 [ 146.65275574]
 [ 190.73953247]
 [ 152.68650818]
 [ 171.93385315]
 [ 178.20524597]
 [ 158.24415588]
 [ 171.42416382]
 [ 176.32922363]
 [ 162.70065308]
 [ 152.03469849]
 [ 194.75515747]]
740 cost:  27.5125 
 hypothesis: 
 [[ 149.76452637]
 [ 188.99047852]
 [ 181.79

1130 cost:  23.6208 
 hypothesis: 
 [[ 150.00038147]
 [ 188.62219238]
 [ 181.75653076]
 [ 198.01304626]
 [ 145.41862488]
 [ 107.38784027]
 [ 145.28340149]
 [ 103.56260681]
 [ 177.82582092]
 [ 164.98832703]
 [ 142.37965393]
 [ 143.80151367]
 [ 188.12239075]
 [ 156.743927  ]
 [ 147.12840271]
 [ 190.58842468]
 [ 151.78358459]
 [ 172.86607361]
 [ 178.05108643]
 [ 158.21124268]
 [ 171.91311646]
 [ 176.19239807]
 [ 163.17245483]
 [ 151.82905579]
 [ 194.38334656]]
1140 cost:  23.5309 
 hypothesis: 
 [[ 150.00624084]
 [ 188.6131897 ]
 [ 181.75558472]
 [ 198.01620483]
 [ 145.40429688]
 [ 107.38188171]
 [ 145.29652405]
 [ 103.58782959]
 [ 177.81881714]
 [ 164.98968506]
 [ 142.38320923]
 [ 143.79954529]
 [ 188.11680603]
 [ 156.73217773]
 [ 147.13964844]
 [ 190.58477783]
 [ 151.76231384]
 [ 172.88819885]
 [ 178.04756165]
 [ 158.21058655]
 [ 171.92471313]
 [ 176.18907166]
 [ 163.18365479]
 [ 151.82440186]
 [ 194.37454224]]
1150 cost:  23.4414 
 hypothesis: 
 [[ 150.01208496]
 [ 188.60417175]
 [ 181

1550 cost:  20.2138 
 hypothesis: 
 [[ 150.23777771]
 [ 188.26057434]
 [ 181.71998596]
 [ 198.1388855 ]
 [ 144.84538269]
 [ 107.14552307]
 [ 145.80589294]
 [ 104.56775665]
 [ 177.54039001]
 [ 165.03257751]
 [ 142.51991272]
 [ 143.7179718 ]
 [ 187.9025116 ]
 [ 156.27940369]
 [ 147.57502747]
 [ 190.43951416]
 [ 150.93875122]
 [ 173.74795532]
 [ 177.91468811]
 [ 158.18943787]
 [ 172.37388611]
 [ 176.05680847]
 [ 163.61923218]
 [ 151.65072632]
 [ 194.03140259]]
1560 cost:  20.1412 
 hypothesis: 
 [[ 150.2432251 ]
 [ 188.25238037]
 [ 181.71920776]
 [ 198.14172363]
 [ 144.83241272]
 [ 107.13995361]
 [ 145.81765747]
 [ 104.59039307]
 [ 177.53382874]
 [ 165.03335571]
 [ 142.52305603]
 [ 143.71598816]
 [ 187.89762878]
 [ 156.26905823]
 [ 147.58503723]
 [ 190.43609619]
 [ 150.91981506]
 [ 173.76782227]
 [ 177.91171265]
 [ 158.18904114]
 [ 172.38423157]
 [ 176.05368042]
 [ 163.62930298]
 [ 151.6468811 ]
 [ 194.02348328]]
1570 cost:  20.0691 
 hypothesis: 
 [[ 150.24865723]
 [ 188.24420166]
 [ 181

1960 cost:  17.5229 
 hypothesis: 
 [[ 150.45321655]
 [ 187.93971252]
 [ 181.69088745]
 [ 198.24984741]
 [ 144.33885193]
 [ 106.92470551]
 [ 146.26412964]
 [ 105.44908142]
 [ 177.28048706]
 [ 165.05560303]
 [ 142.641922  ]
 [ 143.63722229]
 [ 187.7151947 ]
 [ 155.8795166 ]
 [ 147.96456909]
 [ 190.30378723]
 [ 150.20428467]
 [ 174.52264404]
 [ 177.80265808]
 [ 158.17796326]
 [ 172.77716064]
 [ 175.93261719]
 [ 164.01208496]
 [ 151.50744629]
 [ 193.72209167]]
1970 cost:  17.464 
 hypothesis: 
 [[ 150.45826721]
 [ 187.93225098]
 [ 181.69024658]
 [ 198.25242615]
 [ 144.32711792]
 [ 106.91950989]
 [ 146.27471924]
 [ 105.46942902]
 [ 177.27438354]
 [ 165.05593872]
 [ 142.64472961]
 [ 143.63526917]
 [ 187.71092224]
 [ 155.87036133]
 [ 147.97354126]
 [ 190.30059814]
 [ 150.18739319]
 [ 174.54052734]
 [ 177.80015564]
 [ 158.17779541]
 [ 172.78645325]
 [ 175.9296875 ]
 [ 164.02116394]
 [ 151.50427246]
 [ 193.7149353 ]]
1980 cost:  17.4055 
 hypothesis: 
 [[ 150.46333313]
 [ 187.92481995]
 [ 181.

2380 cost:  15.291 
 hypothesis: 
 [[ 150.6577301 ]
 [ 187.6411438 ]
 [ 181.66661072]
 [ 198.35250854]
 [ 143.86933899]
 [ 106.71434021]
 [ 146.68597412]
 [ 106.26023102]
 [ 177.03303528]
 [ 165.06329346]
 [ 142.75338745]
 [ 143.55648804]
 [ 187.54745483]
 [ 155.51776123]
 [ 148.32136536]
 [ 190.17443848]
 [ 149.53364563]
 [ 175.23684692]
 [ 177.70599365]
 [ 158.1739502 ]
 [ 173.14767456]
 [ 175.81381226]
 [ 164.37458801]
 [ 151.38671875]
 [ 193.43673706]]
2390 cost:  15.2434 
 hypothesis: 
 [[ 150.66239929]
 [ 187.6343689 ]
 [ 181.66610718]
 [ 198.35482788]
 [ 143.85873413]
 [ 106.70952606]
 [ 146.69549561]
 [ 106.27849579]
 [ 177.02737427]
 [ 165.06330872]
 [ 142.75588989]
 [ 143.55459595]
 [ 187.54373169]
 [ 155.50970459]
 [ 148.32937622]
 [ 190.17147827]
 [ 149.51861572]
 [ 175.25292969]
 [ 177.70388794]
 [ 158.17391968]
 [ 173.15602112]
 [ 175.81108093]
 [ 164.38275146]
 [ 151.38412476]
 [ 193.43032837]]
2400 cost:  15.1961 
 hypothesis: 
 [[ 150.66706848]
 [ 187.62762451]
 [ 181.

 [ 193.18013   ]]
2810 cost:  13.449 
 hypothesis: 
 [[ 150.85084534]
 [ 187.36427307]
 [ 181.64653015]
 [ 198.44717407]
 [ 143.43554688]
 [ 106.5150528 ]
 [ 147.07324219]
 [ 107.00463867]
 [ 176.79876709]
 [ 165.05859375]
 [ 142.85496521]
 [ 143.4768219 ]
 [ 187.39759827]
 [ 155.19129944]
 [ 148.64729309]
 [ 190.05189514]
 [ 148.92288208]
 [ 175.89335632]
 [ 177.62294006]
 [ 158.1759491 ]
 [ 173.48719788]
 [ 175.70082092]
 [ 164.70811462]
 [ 151.28565979]
 [ 193.17433167]]
2820 cost:  13.4108 
 hypothesis: 
 [[ 150.85513306]
 [ 187.35816956]
 [ 181.64613342]
 [ 198.44926453]
 [ 143.42597961]
 [ 106.51060486]
 [ 147.08174133]
 [ 107.02098846]
 [ 176.79354858]
 [ 165.05836487]
 [ 142.85717773]
 [ 143.4750061 ]
 [ 187.39434814]
 [ 155.18418884]
 [ 148.6544342 ]
 [ 190.04916382]
 [ 148.90951538]
 [ 175.90779114]
 [ 177.62117004]
 [ 158.17607117]
 [ 173.49464417]
 [ 175.69828796]
 [ 164.71543884]
 [ 151.28355408]
 [ 193.16856384]]
2830 cost:  13.3727 
 hypothesis: 
 [[ 150.85943604]
 [ 187

 [[ 151.01243591]
 [ 187.13624573]
 [ 181.63174438]
 [ 198.52479553]
 [ 143.07933044]
 [ 106.3478241 ]
 [ 147.3894043 ]
 [ 107.61225891]
 [ 176.60229492]
 [ 165.0461731 ]
 [ 142.93734741]
 [ 143.40769958]
 [ 187.27825928]
 [ 154.92886353]
 [ 148.91221619]
 [ 189.94906616]
 [ 148.42776489]
 [ 176.43003845]
 [ 177.55923462]
 [ 158.1817627 ]
 [ 173.76391602]
 [ 175.60571289]
 [ 164.98094177]
 [ 151.21031189]
 [ 192.9597168 ]]
3210 cost:  12.0606 
 hypothesis: 
 [[ 151.01641846]
 [ 187.13067627]
 [ 181.63140869]
 [ 198.52667236]
 [ 143.07063293]
 [ 106.34370422]
 [ 147.39709473]
 [ 107.62705994]
 [ 176.59744263]
 [ 165.04577637]
 [ 142.93934631]
 [ 143.40597534]
 [ 187.27539062]
 [ 154.92251587]
 [ 148.9186554 ]
 [ 189.94651794]
 [ 148.41574097]
 [ 176.44311523]
 [ 177.55773926]
 [ 158.1819458 ]
 [ 173.7706604 ]
 [ 175.60336304]
 [ 164.9875946 ]
 [ 151.20855713]
 [ 192.95449829]]
3220 cost:  12.0294 
 hypothesis: 
 [[ 151.020401  ]
 [ 187.12510681]
 [ 181.631073  ]
 [ 198.52857971]
 [ 143.

3610 cost:  10.9264 
 hypothesis: 
 [[ 151.16918945]
 [ 186.91809082]
 [ 181.61909485]
 [ 198.59872437]
 [ 142.73950195]
 [ 106.1852417 ]
 [ 147.68943787]
 [ 108.18880463]
 [ 176.41134644]
 [ 165.02697754]
 [ 143.01504517]
 [ 143.33860779]
 [ 187.16757202]
 [ 154.68328857]
 [ 149.16262817]
 [ 189.84906006]
 [ 147.96087646]
 [ 176.93994141]
 [ 177.50234985]
 [ 158.19085693]
 [ 174.02615356]
 [ 175.51296997]
 [ 165.24035645]
 [ 151.14489746]
 [ 192.7557373 ]]
3620 cost:  10.9009 
 hypothesis: 
 [[ 151.1728363 ]
 [ 186.9130249 ]
 [ 181.61882019]
 [ 198.60043335]
 [ 142.73162842]
 [ 106.18144226]
 [ 147.69638062]
 [ 108.20212555]
 [ 176.40689087]
 [ 165.02645874]
 [ 143.0168457 ]
 [ 143.3369751 ]
 [ 187.16503906]
 [ 154.67765808]
 [ 149.168396  ]
 [ 189.84671021]
 [ 147.95013428]
 [ 176.95173645]
 [ 177.50106812]
 [ 158.19110107]
 [ 174.0322113 ]
 [ 175.51080322]
 [ 165.24633789]
 [ 151.14346313]
 [ 192.7510376 ]]
3630 cost:  10.8755 
 hypothesis: 
 [[ 151.17649841]
 [ 186.90795898]
 [ 181

 [ 192.58030701]]
4010 cost:  9.99945 
 hypothesis: 
 [[ 151.30987549]
 [ 186.72473145]
 [ 181.6091156 ]
 [ 198.66400146]
 [ 142.43910217]
 [ 106.03900909]
 [ 147.95339966]
 [ 108.69590759]
 [ 176.23968506]
 [ 165.0039978 ]
 [ 143.08303833]
 [ 143.27493286]
 [ 187.07235718]
 [ 154.47015381]
 [ 149.3821106 ]
 [ 189.75909424]
 [ 147.5526886 ]
 [ 177.38899231]
 [ 177.45523071]
 [ 158.20181274]
 [ 174.25653076]
 [ 175.42938232]
 [ 165.46893311]
 [ 151.09243774]
 [ 192.5760498 ]]
4020 cost:  9.97857 
 hypothesis: 
 [[ 151.31324768]
 [ 186.72012329]
 [ 181.60888672]
 [ 198.66555786]
 [ 142.43197632]
 [ 106.0355072 ]
 [ 147.95965576]
 [ 108.70793915]
 [ 176.23556519]
 [ 165.00338745]
 [ 143.0846405 ]
 [ 143.27339172]
 [ 187.07011414]
 [ 154.46513367]
 [ 149.38729858]
 [ 189.75692749]
 [ 147.54304504]
 [ 177.3996582 ]
 [ 177.4541626 ]
 [ 158.20211792]
 [ 174.26199341]
 [ 175.42736816]
 [ 165.47436523]
 [ 151.09126282]
 [ 192.57177734]]
4030 cost:  9.95782 
 hypothesis: 
 [[ 151.31658936]
 [ 18

4390 cost:  9.27605 
 hypothesis: 
 [[ 151.43302917]
 [ 186.55731201]
 [ 181.60140991]
 [ 198.72032166]
 [ 142.17961121]
 [ 105.91075134]
 [ 148.18041992]
 [ 109.13195038]
 [ 176.08917236]
 [ 164.97952271]
 [ 143.14120483]
 [ 143.21792603]
 [ 186.99209595]
 [ 154.28909302]
 [ 149.57022095]
 [ 189.6802063 ]
 [ 147.20355225]
 [ 177.77555847]
 [ 177.41699219]
 [ 158.21353149]
 [ 174.45440674]
 [ 175.355896  ]
 [ 165.66583252]
 [ 151.05123901]
 [ 192.42129517]]
4400 cost:  9.25883 
 hypothesis: 
 [[ 151.43612671]
 [ 186.55311584]
 [ 181.60122681]
 [ 198.72172546]
 [ 142.1730957 ]
 [ 105.90750885]
 [ 148.18609619]
 [ 109.14286804]
 [ 176.08537292]
 [ 164.97885132]
 [ 143.14263916]
 [ 143.21647644]
 [ 186.9901123 ]
 [ 154.28459167]
 [ 149.5749054 ]
 [ 189.67822266]
 [ 147.19482422]
 [ 177.78523254]
 [ 177.4160614 ]
 [ 158.21383667]
 [ 174.45935059]
 [ 175.35403442]
 [ 165.67074585]
 [ 151.05026245]
 [ 192.41741943]]
4410 cost:  9.24168 
 hypothesis: 
 [[ 151.4392395 ]
 [ 186.54891968]
 [ 181

4750 cost:  8.70727 
 hypothesis: 
 [[ 151.54084778]
 [ 186.41215515]
 [ 181.59544373]
 [ 198.76901245]
 [ 141.95504761]
 [ 105.79827881]
 [ 148.37612915]
 [ 109.50782776]
 [ 175.95724487]
 [ 164.95481873]
 [ 143.19111633]
 [ 143.167099  ]
 [ 186.92417908]
 [ 154.13468933]
 [ 149.73188782]
 [ 189.61102295]
 [ 146.90400696]
 [ 178.1091156 ]
 [ 177.38574219]
 [ 158.22535706]
 [ 174.62483215]
 [ 175.29136658]
 [ 165.83580017]
 [ 151.01869202]
 [ 192.28773499]]
4760 cost:  8.6929 
 hypothesis: 
 [[ 151.54371643]
 [ 186.40829468]
 [ 181.59529114]
 [ 198.77030945]
 [ 141.94908142]
 [ 105.7952652 ]
 [ 148.38130188]
 [ 109.51776886]
 [ 175.95372009]
 [ 164.95411682]
 [ 143.19242859]
 [ 143.16572571]
 [ 186.9223938 ]
 [ 154.13063049]
 [ 149.73616028]
 [ 189.60917664]
 [ 146.89608765]
 [ 178.1179657 ]
 [ 177.38493347]
 [ 158.22567749]
 [ 174.6293335 ]
 [ 175.28964233]
 [ 165.84030151]
 [ 151.01786804]
 [ 192.28419495]]
4770 cost:  8.67859 
 hypothesis: 
 [[ 151.54656982]
 [ 186.40441895]
 [ 181.

5110 cost:  8.23267 
 hypothesis: 
 [[ 151.64057922]
 [ 186.27900696]
 [ 181.59054565]
 [ 198.81355286]
 [ 141.74940491]
 [ 105.6940918 ]
 [ 148.55471802]
 [ 109.85076141]
 [ 175.83506775]
 [ 164.92930603]
 [ 143.23646545]
 [ 143.11929321]
 [ 186.86323547]
 [ 153.995224  ]
 [ 149.87904358]
 [ 189.54692078]
 [ 146.63191223]
 [ 178.41372681]
 [ 177.35865784]
 [ 158.2375946 ]
 [ 174.78016663]
 [ 175.23149109]
 [ 165.99110413]
 [ 150.99145508]
 [ 192.16575623]]
5120 cost:  8.22067 
 hypothesis: 
 [[ 151.64324951]
 [ 186.27545166]
 [ 181.59040833]
 [ 198.81472778]
 [ 141.74395752]
 [ 105.69130707]
 [ 148.55944824]
 [ 109.85984802]
 [ 175.83180237]
 [ 164.92858887]
 [ 143.2376709 ]
 [ 143.11799622]
 [ 186.86161804]
 [ 153.99154663]
 [ 149.88291931]
 [ 189.54521179]
 [ 146.62471008]
 [ 178.42179871]
 [ 177.35795593]
 [ 158.2379303 ]
 [ 174.78427124]
 [ 175.22988892]
 [ 165.99520874]
 [ 150.99076843]
 [ 192.1625061 ]]
5130 cost:  8.20874 
 hypothesis: 
 [[ 151.64590454]
 [ 186.27192688]
 [ 181

5500 cost:  7.80672 
 hypothesis: 
 [[ 151.74012756]
 [ 186.14717102]
 [ 181.58625793]
 [ 198.85752869]
 [ 141.54618835]
 [ 105.58997345]
 [ 148.73060608]
 [ 110.18849182]
 [ 175.71298218]
 [ 164.90132141]
 [ 143.28096008]
 [ 143.07086182]
 [ 186.80419922]
 [ 153.85919189]
 [ 150.02355957]
 [ 189.48287964]
 [ 146.36506653]
 [ 178.713974  ]
 [ 177.33334351]
 [ 158.25102234]
 [ 174.93302917]
 [ 175.17155457]
 [ 166.14422607]
 [ 150.96699524]
 [ 192.04545593]]
5510 cost:  7.79687 
 hypothesis: 
 [[ 151.74256897]
 [ 186.14393616]
 [ 181.58616638]
 [ 198.8585968 ]
 [ 141.54124451]
 [ 105.5874176 ]
 [ 148.73490906]
 [ 110.19671631]
 [ 175.7099762 ]
 [ 164.90061951]
 [ 143.28204346]
 [ 143.06967163]
 [ 186.80278015]
 [ 153.855896  ]
 [ 150.02708435]
 [ 189.48130798]
 [ 146.35856628]
 [ 178.7212677 ]
 [ 177.33274841]
 [ 158.25135803]
 [ 174.93673706]
 [ 175.17008972]
 [ 166.14796448]
 [ 150.96643066]
 [ 192.04252625]]
5520 cost:  7.78703 
 hypothesis: 
 [[ 151.74499512]
 [ 186.14071655]
 [ 181

5830 cost:  7.50601 
 hypothesis: 
 [[ 151.81788635]
 [ 186.04490662]
 [ 181.58331299]
 [ 198.89157104]
 [ 141.38879395]
 [ 105.50850677]
 [ 148.86643982]
 [ 110.44923401]
 [ 175.61750793]
 [ 164.87776184]
 [ 143.31518555]
 [ 143.03251648]
 [ 186.75930786]
 [ 153.75508118]
 [ 150.13490295]
 [ 189.43278503]
 [ 146.1598053 ]
 [ 178.94596863]
 [ 177.3147583 ]
 [ 158.26235962]
 [ 175.0509491 ]
 [ 175.12461853]
 [ 166.26261902]
 [ 150.94973755]
 [ 191.95249939]]
5840 cost:  7.49767 
 hypothesis: 
 [[ 151.82015991]
 [ 186.04190063]
 [ 181.58322144]
 [ 198.89254761]
 [ 141.38421631]
 [ 105.50611877]
 [ 148.87036133]
 [ 110.45678711]
 [ 175.61471558]
 [ 164.87701416]
 [ 143.31616211]
 [ 143.03137207]
 [ 186.75799561]
 [ 153.7520752 ]
 [ 150.13812256]
 [ 189.43130493]
 [ 146.15383911]
 [ 178.95266724]
 [ 177.31420898]
 [ 158.26266479]
 [ 175.05435181]
 [ 175.12322998]
 [ 166.26602173]
 [ 150.94924927]
 [ 191.94979858]]
5850 cost:  7.48935 
 hypothesis: 
 [[ 151.82241821]
 [ 186.03897095]
 [ 181

6140 cost:  7.2655 
 hypothesis: 
 [[ 151.88592529]
 [ 185.95600891]
 [ 181.58106995]
 [ 198.92112732]
 [ 141.25212097]
 [ 105.43719482]
 [ 148.98408508]
 [ 110.67504883]
 [ 175.53398132]
 [ 164.85588074]
 [ 143.34474182]
 [ 142.99862671]
 [ 186.72096252]
 [ 153.6656189 ]
 [ 150.23112488]
 [ 189.38893127]
 [ 145.9826355 ]
 [ 179.14703369]
 [ 177.29937744]
 [ 158.27287292]
 [ 175.1530304 ]
 [ 175.08351135]
 [ 166.36523438]
 [ 150.93600464]
 [ 191.87193298]]
6150 cost:  7.25835 
 hypothesis: 
 [[ 151.88804626]
 [ 185.95323181]
 [ 181.58097839]
 [ 198.92204285]
 [ 141.24787903]
 [ 105.43496704]
 [ 148.98771667]
 [ 110.68203735]
 [ 175.53135681]
 [ 164.85517883]
 [ 143.34565735]
 [ 142.99757385]
 [ 186.71977234]
 [ 153.66285706]
 [ 150.2341156 ]
 [ 189.38755798]
 [ 145.97715759]
 [ 179.15324402]
 [ 177.29890442]
 [ 158.27320862]
 [ 175.15617371]
 [ 175.0821991 ]
 [ 166.3684082 ]
 [ 150.93559265]
 [ 191.86943054]]
6160 cost:  7.25124 
 hypothesis: 
 [[ 151.89013672]
 [ 185.95046997]
 [ 181.

6480 cost:  7.04131 
 hypothesis: 
 [[ 151.95523071]
 [ 185.86584473]
 [ 181.57897949]
 [ 198.95098877]
 [ 141.1137085 ]
 [ 105.36440277]
 [ 149.10290527]
 [ 110.90310669]
 [ 175.44869995]
 [ 164.83239746]
 [ 143.3744812 ]
 [ 142.9637146 ]
 [ 186.68264771]
 [ 153.57583618]
 [ 150.328125  ]
 [ 189.34414673]
 [ 145.80419922]
 [ 179.35021973]
 [ 177.28445435]
 [ 158.28411865]
 [ 175.25604248]
 [ 175.04147339]
 [ 166.46896362]
 [ 150.92324829]
 [ 191.79046631]]
6490 cost:  7.03528 
 hypothesis: 
 [[ 151.95721436]
 [ 185.86332703]
 [ 181.57894897]
 [ 198.95184326]
 [ 141.10983276]
 [ 105.36235046]
 [ 149.10624695]
 [ 110.90953064]
 [ 175.44631958]
 [ 164.83172607]
 [ 143.37532043]
 [ 142.96273804]
 [ 186.68157959]
 [ 153.573349  ]
 [ 150.33087158]
 [ 189.34291077]
 [ 145.79919434]
 [ 179.35594177]
 [ 177.28405762]
 [ 158.28448486]
 [ 175.25894165]
 [ 175.04029846]
 [ 166.47189331]
 [ 150.9229126 ]
 [ 191.78819275]]
6500 cost:  7.02928 
 hypothesis: 
 [[ 151.95916748]
 [ 185.86079407]
 [ 181

6850 cost:  6.83708 
 hypothesis: 
 [[ 152.02487183]
 [ 185.77586365]
 [ 181.57723999]
 [ 198.98080444]
 [ 140.97572327]
 [ 105.29127502]
 [ 149.22111511]
 [ 111.12997437]
 [ 175.36308289]
 [ 164.80766296]
 [ 143.40400696]
 [ 142.92834473]
 [ 186.64508057]
 [ 153.48725891]
 [ 150.42446899]
 [ 189.29920959]
 [ 145.62728882]
 [ 179.55247498]
 [ 177.27030945]
 [ 158.29605103]
 [ 175.35845947]
 [ 174.99923706]
 [ 166.57228088]
 [ 150.91172791]
 [ 191.70941162]]
6860 cost:  6.83207 
 hypothesis: 
 [[ 152.02668762]
 [ 185.77357483]
 [ 181.57722473]
 [ 198.98158264]
 [ 140.97216797]
 [ 105.28939056]
 [ 149.22416687]
 [ 111.13582611]
 [ 175.36088562]
 [ 164.80702209]
 [ 143.4047699 ]
 [ 142.92744446]
 [ 186.64413452]
 [ 153.48500061]
 [ 150.42695618]
 [ 189.29806519]
 [ 145.62275696]
 [ 179.55770874]
 [ 177.26997375]
 [ 158.29637146]
 [ 175.36112976]
 [ 174.99815369]
 [ 166.57493591]
 [ 150.91146851]
 [ 191.70733643]]
6870 cost:  6.82708 
 hypothesis: 
 [[ 152.0284729 ]
 [ 185.77124023]
 [ 181

7230 cost:  6.66325 
 hypothesis: 
 [[ 152.09049988]
 [ 185.69151306]
 [ 181.57583618]
 [ 199.00869751]
 [ 140.84648132]
 [ 105.22229004]
 [ 149.33155823]
 [ 111.3418808 ]
 [ 175.28230286]
 [ 164.78326416]
 [ 143.4315033 ]
 [ 142.8946991 ]
 [ 186.61042786]
 [ 153.40510559]
 [ 150.51426697]
 [ 189.25679016]
 [ 145.46257019]
 [ 179.74153137]
 [ 177.25770569]
 [ 158.30780029]
 [ 175.45407104]
 [ 174.95933533]
 [ 166.66885376]
 [ 150.90205383]
 [ 191.63362122]]
7240 cost:  6.6591 
 hypothesis: 
 [[ 152.09214783]
 [ 185.68940735]
 [ 181.57582092]
 [ 199.00938416]
 [ 140.84324646]
 [ 105.22055054]
 [ 149.33432007]
 [ 111.34718323]
 [ 175.28027344]
 [ 164.78265381]
 [ 143.43218994]
 [ 142.8938446 ]
 [ 186.60955811]
 [ 153.40306091]
 [ 150.51652527]
 [ 189.2557373 ]
 [ 145.45845032]
 [ 179.7462616 ]
 [ 177.25740051]
 [ 158.30810547]
 [ 175.45646667]
 [ 174.95834351]
 [ 166.67127991]
 [ 150.90182495]
 [ 191.63172913]]
7250 cost:  6.65499 
 hypothesis: 
 [[ 152.09378052]
 [ 185.68727112]
 [ 181.

7590 cost:  6.52645 
 hypothesis: 
 [[ 152.14758301]
 [ 185.61849976]
 [ 181.5748291 ]
 [ 199.0328064 ]
 [ 140.73475647]
 [ 105.16222382]
 [ 149.42681885]
 [ 111.52468872]
 [ 175.21200562]
 [ 164.76119995]
 [ 143.45513916]
 [ 142.86517334]
 [ 186.58088684]
 [ 153.3347168 ]
 [ 150.59162903]
 [ 189.21986389]
 [ 145.32086182]
 [ 179.9046936 ]
 [ 177.24734497]
 [ 158.31842041]
 [ 175.53651428]
 [ 174.92457581]
 [ 166.75224304]
 [ 150.89453125]
 [ 191.56819153]]
7600 cost:  6.52297 
 hypothesis: 
 [[ 152.14907837]
 [ 185.61654663]
 [ 181.57479858]
 [ 199.03341675]
 [ 140.73178101]
 [ 105.16061401]
 [ 149.42935181]
 [ 111.52952576]
 [ 175.21011353]
 [ 164.7605896 ]
 [ 143.45578003]
 [ 142.86437988]
 [ 186.58007812]
 [ 153.33282471]
 [ 150.59365845]
 [ 189.21887207]
 [ 145.31707764]
 [ 179.9090271 ]
 [ 177.24707031]
 [ 158.31872559]
 [ 175.53869629]
 [ 174.92364502]
 [ 166.75445557]
 [ 150.89434814]
 [ 191.56643677]]
7610 cost:  6.51954 
 hypothesis: 
 [[ 152.15061951]
 [ 185.61460876]
 [ 181

7960 cost:  6.4093 
 hypothesis: 
 [[ 152.20147705]
 [ 185.54983521]
 [ 181.57403564]
 [ 199.05541992]
 [ 140.62979126]
 [ 105.10545349]
 [ 149.51612854]
 [ 111.69602966]
 [ 175.14555359]
 [ 164.73962402]
 [ 143.47724915]
 [ 142.83708191]
 [ 186.55348206]
 [ 153.26913452]
 [ 150.66400146]
 [ 189.18496704]
 [ 145.18836975]
 [ 180.057724  ]
 [ 177.23803711]
 [ 158.32881165]
 [ 175.61373901]
 [ 174.89169312]
 [ 166.83047485]
 [ 150.88821411]
 [ 191.50682068]]
7970 cost:  6.40643 
 hypothesis: 
 [[ 152.20288086]
 [ 185.54804993]
 [ 181.57400513]
 [ 199.05599976]
 [ 140.62709045]
 [ 105.10398102]
 [ 149.51843262]
 [ 111.70043945]
 [ 175.14382935]
 [ 164.73907471]
 [ 143.47781372]
 [ 142.83636475]
 [ 186.55279541]
 [ 153.2674408 ]
 [ 150.66586304]
 [ 189.18405151]
 [ 145.18495178]
 [ 180.06166077]
 [ 177.23779297]
 [ 158.32907104]
 [ 175.61572266]
 [ 174.89085388]
 [ 166.83248901]
 [ 150.88806152]
 [ 191.50524902]]
7980 cost:  6.40356 
 hypothesis: 
 [[ 152.20425415]
 [ 185.54629517]
 [ 181.

8290 cost:  6.32164 
 hypothesis: 
 [[ 152.24578857]
 [ 185.49363708]
 [ 181.5735321 ]
 [ 199.07394409]
 [ 140.54396057]
 [ 105.05873871]
 [ 149.58903503]
 [ 111.83588409]
 [ 175.09094238]
 [ 164.72138977]
 [ 143.49526978]
 [ 142.81385803]
 [ 186.53138733]
 [ 153.21589661]
 [ 150.7230072 ]
 [ 189.15629578]
 [ 145.08045959]
 [ 180.18273926]
 [ 177.23075867]
 [ 158.33760071]
 [ 175.67677307]
 [ 174.8646698 ]
 [ 166.89439392]
 [ 150.8835907 ]
 [ 191.45671082]]
8300 cost:  6.3192 
 hypothesis: 
 [[ 152.24708557]
 [ 185.49198914]
 [ 181.57350159]
 [ 199.07444763]
 [ 140.54145813]
 [ 105.05735779]
 [ 149.59114075]
 [ 111.83992767]
 [ 175.08932495]
 [ 164.72084045]
 [ 143.49577332]
 [ 142.81315613]
 [ 186.53071594]
 [ 153.21434021]
 [ 150.72471619]
 [ 189.15542603]
 [ 145.07731628]
 [ 180.18635559]
 [ 177.23054504]
 [ 158.33784485]
 [ 175.67858887]
 [ 174.86384583]
 [ 166.89622498]
 [ 150.88345337]
 [ 191.45524597]]
8310 cost:  6.31677 
 hypothesis: 
 [[ 152.24836731]
 [ 185.4903717 ]
 [ 181.

8660 cost:  6.23912 
 hypothesis: 
 [[ 152.29153442]
 [ 185.43579102]
 [ 181.5730896 ]
 [ 199.09295654]
 [ 140.45565796]
 [ 105.01043701]
 [ 149.66387939]
 [ 111.97943115]
 [ 175.03445435]
 [ 164.70199585]
 [ 143.51370239]
 [ 142.78967285]
 [ 186.50888062]
 [ 153.16152954]
 [ 150.78347778]
 [ 189.12661743]
 [ 144.96992493]
 [ 180.31109619]
 [ 177.22357178]
 [ 158.34692383]
 [ 175.74142456]
 [ 174.83666992]
 [ 166.96002197]
 [ 150.87934875]
 [ 191.40524292]]
8670 cost:  6.2371 
 hypothesis: 
 [[ 152.29273987]
 [ 185.43431091]
 [ 181.57310486]
 [ 199.09346008]
 [ 140.4533844 ]
 [ 105.00919342]
 [ 149.66581726]
 [ 111.98313904]
 [ 175.03302002]
 [ 164.70152283]
 [ 143.51417542]
 [ 142.78904724]
 [ 186.50831604]
 [ 153.16014099]
 [ 150.78504944]
 [ 189.12586975]
 [ 144.96708679]
 [ 180.31440735]
 [ 177.22341919]
 [ 158.34718323]
 [ 175.74311829]
 [ 174.83595276]
 [ 166.9617157 ]
 [ 150.8792572 ]
 [ 191.40391541]]
8680 cost:  6.23507 
 hypothesis: 
 [[ 152.29389954]
 [ 185.43281555]
 [ 181.

 [[ 152.32913208]
 [ 185.38845825]
 [ 181.57284546]
 [ 199.10852051]
 [ 140.38343811]
 [ 104.97074127]
 [ 149.72497559]
 [ 112.09663391]
 [ 174.98806763]
 [ 164.68571472]
 [ 143.52871704]
 [ 142.7696991 ]
 [ 186.49066162]
 [ 153.11737061]
 [ 150.83279419]
 [ 189.10223389]
 [ 144.87988281]
 [ 180.41595459]
 [ 177.21795654]
 [ 158.35476685]
 [ 175.79421997]
 [ 174.81365967]
 [ 167.01364136]
 [ 150.87628174]
 [ 191.3631897 ]]
9000 cost:  6.17564 
 hypothesis: 
 [[ 152.33023071]
 [ 185.38708496]
 [ 181.57286072]
 [ 199.10897827]
 [ 140.38134766]
 [ 104.9695816 ]
 [ 149.72676086]
 [ 112.10003662]
 [ 174.98672485]
 [ 164.6852417 ]
 [ 143.52914429]
 [ 142.76913452]
 [ 186.49014282]
 [ 153.11608887]
 [ 150.83422852]
 [ 189.10153198]
 [ 144.87727356]
 [ 180.41900635]
 [ 177.21780396]
 [ 158.35499573]
 [ 175.79574585]
 [ 174.81298828]
 [ 167.01519775]
 [ 150.87619019]
 [ 191.36196899]]
9010 cost:  6.17392 
 hypothesis: 
 [[ 152.33131409]
 [ 185.38572693]
 [ 181.57286072]
 [ 199.10942078]
 [ 140.

9310 cost:  6.12645 
 hypothesis: 
 [[ 152.36286926]
 [ 185.34606934]
 [ 181.57270813]
 [ 199.12242126]
 [ 140.3188324 ]
 [ 104.93506622]
 [ 149.77958679]
 [ 112.20133972]
 [ 174.94639587]
 [ 164.67079163]
 [ 143.542099  ]
 [ 142.75169373]
 [ 186.47453308]
 [ 153.07807922]
 [ 150.87680054]
 [ 189.08035278]
 [ 144.79954529]
 [ 180.50965881]
 [ 177.21308899]
 [ 158.36195374]
 [ 175.84133911]
 [ 174.79298401]
 [ 167.06158447]
 [ 150.87384033]
 [ 191.3256073 ]]
9320 cost:  6.125 
 hypothesis: 
 [[ 152.36390686]
 [ 185.34481812]
 [ 181.57270813]
 [ 199.12287903]
 [ 140.31690979]
 [ 104.93400574]
 [ 149.78123474]
 [ 112.20449066]
 [ 174.94514465]
 [ 164.67036438]
 [ 143.54252625]
 [ 142.75115967]
 [ 186.47407532]
 [ 153.07691956]
 [ 150.87814331]
 [ 189.07971191]
 [ 144.79716492]
 [ 180.51249695]
 [ 177.21296692]
 [ 158.36216736]
 [ 175.84275818]
 [ 174.79237366]
 [ 167.06303406]
 [ 150.87379456]
 [ 191.32449341]]
9330 cost:  6.12353 
 hypothesis: 
 [[ 152.36489868]
 [ 185.34353638]
 [ 181.5

9620 cost:  6.08433 
 hypothesis: 
 [[ 152.39321899]
 [ 185.30809021]
 [ 181.57263184]
 [ 199.13490295]
 [ 140.26094055]
 [ 104.90298462]
 [ 149.82844543]
 [ 112.29503632]
 [ 174.90892029]
 [ 164.65715027]
 [ 143.55407715]
 [ 142.73542786]
 [ 186.46022034]
 [ 153.04307556]
 [ 150.91615295]
 [ 189.0606842 ]
 [ 144.72779846]
 [ 180.59356689]
 [ 177.20892334]
 [ 158.36851501]
 [ 175.88352966]
 [ 174.7743988 ]
 [ 167.10450745]
 [ 150.87191772]
 [ 191.29196167]]
9630 cost:  6.08308 
 hypothesis: 
 [[ 152.39416504]
 [ 185.30691528]
 [ 181.57263184]
 [ 199.13531494]
 [ 140.25915527]
 [ 104.90200043]
 [ 149.82995605]
 [ 112.29795074]
 [ 174.90777588]
 [ 164.65672302]
 [ 143.55444336]
 [ 142.73492432]
 [ 186.45977783]
 [ 153.04199219]
 [ 150.91737366]
 [ 189.06005859]
 [ 144.72558594]
 [ 180.59617615]
 [ 177.20880127]
 [ 158.3687439 ]
 [ 175.88482666]
 [ 174.77381897]
 [ 167.10585022]
 [ 150.87185669]
 [ 191.29092407]]
9640 cost:  6.08182 
 hypothesis: 
 [[ 152.39509583]
 [ 185.3057251 ]
 [ 181

10050 cost:  6.03572 
 hypothesis: 
 [[ 152.43174744]
 [ 185.25996399]
 [ 181.57261658]
 [ 199.15071106]
 [ 140.18766785]
 [ 104.86219788]
 [ 149.89019775]
 [ 112.41345978]
 [ 174.86131287]
 [ 164.63948059]
 [ 143.56916809]
 [ 142.7146759 ]
 [ 186.44226074]
 [ 152.99900818]
 [ 150.96583557]
 [ 189.03565979]
 [ 144.63726807]
 [ 180.69966125]
 [ 177.20381165]
 [ 158.37702942]
 [ 175.93681335]
 [ 174.75074768]
 [ 167.15879822]
 [ 150.86981201]
 [ 191.24942017]]
10060 cost:  6.03471 
 hypothesis: 
 [[ 152.43258667]
 [ 185.25891113]
 [ 181.57260132]
 [ 199.15103149]
 [ 140.18605042]
 [ 104.86129761]
 [ 149.89154053]
 [ 112.4160614 ]
 [ 174.86026001]
 [ 164.6390686 ]
 [ 143.56950378]
 [ 142.71420288]
 [ 186.44186401]
 [ 152.99801636]
 [ 150.96691895]
 [ 189.03509521]
 [ 144.63528442]
 [ 180.70198059]
 [ 177.20370483]
 [ 158.37722778]
 [ 175.93795776]
 [ 174.75021362]
 [ 167.1599884 ]
 [ 150.86976624]
 [ 191.24847412]]
10070 cost:  6.0337 
 hypothesis: 
 [[ 152.43344116]
 [ 185.25785828]
 [ 1

10450 cost:  5.99898 
 hypothesis: 
 [[ 152.46420288]
 [ 185.21955872]
 [ 181.57266235]
 [ 199.16395569]
 [ 140.12615967]
 [ 104.82783508]
 [ 149.94195557]
 [ 112.51268768]
 [ 174.82118225]
 [ 164.6242981 ]
 [ 143.58180237]
 [ 142.69709778]
 [ 186.42733765]
 [ 152.96224976]
 [ 151.00741577]
 [ 189.01460266]
 [ 144.56155396]
 [ 180.78858948]
 [ 177.19970703]
 [ 158.38433838]
 [ 175.98144531]
 [ 174.73080444]
 [ 167.20431519]
 [ 150.86834717]
 [ 191.21377563]]
10460 cost:  5.99816 
 hypothesis: 
 [[ 152.46498108]
 [ 185.21859741]
 [ 181.57267761]
 [ 199.16426086]
 [ 140.12471008]
 [ 104.82701874]
 [ 149.94317627]
 [ 112.51504517]
 [ 174.82022095]
 [ 164.62394714]
 [ 143.58209229]
 [ 142.69668579]
 [ 186.42698669]
 [ 152.96134949]
 [ 151.00839233]
 [ 189.01408386]
 [ 144.55973816]
 [ 180.79069519]
 [ 177.19961548]
 [ 158.38450623]
 [ 175.98249817]
 [ 174.73033142]
 [ 167.20539856]
 [ 150.86833191]
 [ 191.21290588]]
10470 cost:  5.99733 
 hypothesis: 
 [[ 152.46574402]
 [ 185.21765137]
 [ 

10870 cost:  5.96754 
 hypothesis: 
 [[ 152.49508667]
 [ 185.18121338]
 [ 181.57278442]
 [ 199.17651367]
 [ 140.06782532]
 [ 104.79508972]
 [ 149.99095154]
 [ 112.60665894]
 [ 174.7829895 ]
 [ 164.60960388]
 [ 143.59371948]
 [ 142.68029785]
 [ 186.41331482]
 [ 152.92755127]
 [ 151.04675293]
 [ 188.99453735]
 [ 144.4899292 ]
 [ 180.87284851]
 [ 177.19598389]
 [ 158.39141846]
 [ 176.02371216]
 [ 174.71180725]
 [ 167.24745178]
 [ 150.86721802]
 [ 191.17997742]]
10880 cost:  5.96689 
 hypothesis: 
 [[ 152.49578857]
 [ 185.18035889]
 [ 181.57278442]
 [ 199.17680359]
 [ 140.06652832]
 [ 104.7943573 ]
 [ 149.99206543]
 [ 112.60877991]
 [ 174.78213501]
 [ 164.60928345]
 [ 143.5940094 ]
 [ 142.67993164]
 [ 186.4130249 ]
 [ 152.92678833]
 [ 151.04763794]
 [ 188.99407959]
 [ 144.48834229]
 [ 180.87475586]
 [ 177.19590759]
 [ 158.39157104]
 [ 176.0246582 ]
 [ 174.71139526]
 [ 167.24841309]
 [ 150.86720276]
 [ 191.17922974]]
10890 cost:  5.96621 
 hypothesis: 
 [[ 152.49649048]
 [ 185.17948914]
 [ 

11290 cost:  5.94206 
 hypothesis: 
 [[ 152.52301025]
 [ 185.14665222]
 [ 181.57293701]
 [ 199.18783569]
 [ 140.01527405]
 [ 104.76548004]
 [ 150.03507996]
 [ 112.69120789]
 [ 174.74845886]
 [ 164.59613037]
 [ 143.60446167]
 [ 142.66505432]
 [ 186.40080261]
 [ 152.89649963]
 [ 151.08210754]
 [ 188.97639465]
 [ 144.42562866]
 [ 180.94871521]
 [ 177.19276428]
 [ 158.39790344]
 [ 176.0617218 ]
 [ 174.69462585]
 [ 167.2862854 ]
 [ 150.86643982]
 [ 191.14956665]]
11300 cost:  5.94152 
 hypothesis: 
 [[ 152.52363586]
 [ 185.14587402]
 [ 181.57293701]
 [ 199.18807983]
 [ 140.01408386]
 [ 104.76480865]
 [ 150.03607178]
 [ 112.69312286]
 [ 174.74768066]
 [ 164.5958252 ]
 [ 143.60469055]
 [ 142.66470337]
 [ 186.4005127 ]
 [ 152.89578247]
 [ 151.08291626]
 [ 188.97598267]
 [ 144.42416382]
 [ 180.95040894]
 [ 177.19268799]
 [ 158.39804077]
 [ 176.06259155]
 [ 174.69424438]
 [ 167.28715515]
 [ 150.86642456]
 [ 191.14886475]]
11310 cost:  5.94098 
 hypothesis: 
 [[ 152.52426147]
 [ 185.14509583]
 [ 

11630 cost:  5.925 
 hypothesis: 
 [[ 152.54362488]
 [ 185.12120056]
 [ 181.57310486]
 [ 199.19618225]
 [ 139.9765625 ]
 [ 104.74359894]
 [ 150.06752014]
 [ 112.75341034]
 [ 174.72294617]
 [ 164.58604431]
 [ 143.61231995]
 [ 142.65376282]
 [ 186.3916626 ]
 [ 152.87371826]
 [ 151.10810852]
 [ 188.9630127 ]
 [ 144.37837219]
 [ 181.00453186]
 [ 177.19047546]
 [ 158.402771  ]
 [ 176.08970642]
 [ 174.68196106]
 [ 167.31486511]
 [ 150.86598206]
 [ 191.12719727]]
11640 cost:  5.92455 
 hypothesis: 
 [[ 152.54420471]
 [ 185.1204834 ]
 [ 181.57310486]
 [ 199.19644165]
 [ 139.97546387]
 [ 104.74298859]
 [ 150.06845093]
 [ 112.7551651 ]
 [ 174.72225952]
 [ 164.58575439]
 [ 143.61254883]
 [ 142.65345764]
 [ 186.39141846]
 [ 152.87307739]
 [ 151.10882568]
 [ 188.96264648]
 [ 144.37704468]
 [ 181.00610352]
 [ 177.19041443]
 [ 158.40290833]
 [ 176.09049988]
 [ 174.68161011]
 [ 167.31567383]
 [ 150.86598206]
 [ 191.12657166]]
11650 cost:  5.92409 
 hypothesis: 
 [[ 152.5447998 ]
 [ 185.11978149]
 [ 18

12050 cost:  5.90757 
 hypothesis: 
 [[ 152.56684875]
 [ 185.09255981]
 [ 181.57330322]
 [ 199.20558167]
 [ 139.93305969]
 [ 104.71895599]
 [ 150.10395813]
 [ 112.82325745]
 [ 174.69424438]
 [ 164.5745697 ]
 [ 143.62117004]
 [ 142.64100647]
 [ 186.38145447]
 [ 152.84820557]
 [ 151.13728333]
 [ 188.94793701]
 [ 144.32536316]
 [ 181.06724548]
 [ 177.18798828]
 [ 158.40829468]
 [ 176.12110901]
 [ 174.66767883]
 [ 167.34698486]
 [ 150.86561584]
 [ 191.10206604]]
12060 cost:  5.90719 
 hypothesis: 
 [[ 152.56735229]
 [ 185.09190369]
 [ 181.57330322]
 [ 199.20578003]
 [ 139.93206787]
 [ 104.71839142]
 [ 150.1047821 ]
 [ 112.82483673]
 [ 174.69358826]
 [ 164.5743103 ]
 [ 143.62135315]
 [ 142.64071655]
 [ 186.38119507]
 [ 152.84761047]
 [ 151.13793945]
 [ 188.94758606]
 [ 144.32414246]
 [ 181.06864929]
 [ 177.18792725]
 [ 158.40841675]
 [ 176.12181091]
 [ 174.66732788]
 [ 167.34770203]
 [ 150.86560059]
 [ 191.10150146]]
12070 cost:  5.90683 
 hypothesis: 
 [[ 152.56788635]
 [ 185.09126282]
 [ 

12430 cost:  5.89465 
 hypothesis: 
 [[ 152.58589172]
 [ 185.0690918 ]
 [ 181.57347107]
 [ 199.21325684]
 [ 139.89738464]
 [ 104.69868469]
 [ 150.1337738 ]
 [ 112.88040161]
 [ 174.67063904]
 [ 164.56503296]
 [ 143.62837219]
 [ 142.63049316]
 [ 186.37312317]
 [ 152.82737732]
 [ 151.16111755]
 [ 188.93553162]
 [ 144.28201294]
 [ 181.11856079]
 [ 177.18600464]
 [ 158.41288757]
 [ 176.14678955]
 [ 174.65589905]
 [ 167.3732605 ]
 [ 150.86540222]
 [ 191.08149719]]
12440 cost:  5.89435 
 hypothesis: 
 [[ 152.58638   ]
 [ 185.0684967 ]
 [ 181.57350159]
 [ 199.2134552 ]
 [ 139.89649963]
 [ 104.69817352]
 [ 150.13453674]
 [ 112.88182831]
 [ 174.67004395]
 [ 164.56480408]
 [ 143.6285553 ]
 [ 142.63023376]
 [ 186.3729248 ]
 [ 152.82685852]
 [ 151.16172791]
 [ 188.93522644]
 [ 144.28092957]
 [ 181.11984253]
 [ 177.18595886]
 [ 158.41299438]
 [ 176.14744568]
 [ 174.65562439]
 [ 167.37391663]
 [ 150.86540222]
 [ 191.08097839]]
12450 cost:  5.89404 
 hypothesis: 
 [[ 152.58685303]
 [ 185.06791687]
 [ 

 [ 191.06375122]]
12800 cost:  5.88421 
 hypothesis: 
 [[ 152.60284424]
 [ 185.04827881]
 [ 181.57366943]
 [ 199.22007751]
 [ 139.86576843]
 [ 104.6806488 ]
 [ 150.16021729]
 [ 112.93103027]
 [ 174.6496582 ]
 [ 164.55645752]
 [ 143.63476562]
 [ 142.62112427]
 [ 186.36581421]
 [ 152.80899048]
 [ 151.18223572]
 [ 188.92453003]
 [ 144.24365234]
 [ 181.1640625 ]
 [ 177.18432617]
 [ 158.41700745]
 [ 176.16955566]
 [ 174.64546204]
 [ 167.39657593]
 [ 150.86532593]
 [ 191.06326294]]
12810 cost:  5.88396 
 hypothesis: 
 [[ 152.60328674]
 [ 185.04774475]
 [ 181.57368469]
 [ 199.22026062]
 [ 139.86494446]
 [ 104.68019867]
 [ 150.16090393]
 [ 112.93235016]
 [ 174.64912415]
 [ 164.55625916]
 [ 143.63493347]
 [ 142.62088013]
 [ 186.36561584]
 [ 152.80851746]
 [ 151.18278503]
 [ 188.92425537]
 [ 144.24267578]
 [ 181.16523743]
 [ 177.1842804 ]
 [ 158.41712952]
 [ 176.17015076]
 [ 174.64518738]
 [ 167.39717102]
 [ 150.86534119]
 [ 191.06280518]]
12820 cost:  5.88371 
 hypothesis: 
 [[ 152.60371399]
 [

13200 cost:  5.87491 
 hypothesis: 
 [[ 152.61952209]
 [ 185.02781677]
 [ 181.57389832]
 [ 199.22679138]
 [ 139.83470154]
 [ 104.66291046]
 [ 150.18614197]
 [ 112.98073578]
 [ 174.62901306]
 [ 164.54798889]
 [ 143.64102173]
 [ 142.61187744]
 [ 186.35865784]
 [ 152.79096985]
 [ 151.20295715]
 [ 188.91369629]
 [ 144.20603943]
 [ 181.20875549]
 [ 177.18269348]
 [ 158.4210968 ]
 [ 176.19190979]
 [ 174.63517761]
 [ 167.41944885]
 [ 150.86532593]
 [ 191.04537964]]
13210 cost:  5.87469 
 hypothesis: 
 [[ 152.61991882]
 [ 185.02734375]
 [ 181.57389832]
 [ 199.22694397]
 [ 139.83396912]
 [ 104.66248322]
 [ 150.18676758]
 [ 112.98191833]
 [ 174.62852478]
 [ 164.54777527]
 [ 143.64117432]
 [ 142.61164856]
 [ 186.35848999]
 [ 152.7905426 ]
 [ 151.20344543]
 [ 188.91343689]
 [ 144.20515442]
 [ 181.20980835]
 [ 177.18266296]
 [ 158.42118835]
 [ 176.19242859]
 [ 174.63493347]
 [ 167.41999817]
 [ 150.86531067]
 [ 191.04495239]]
13220 cost:  5.87449 
 hypothesis: 
 [[ 152.62030029]
 [ 185.02685547]
 [ 

13620 cost:  5.86695 
 hypothesis: 
 [[ 152.63534546]
 [ 185.00840759]
 [ 181.57409668]
 [ 199.23313904]
 [ 139.80522156]
 [ 104.64601898]
 [ 150.21070862]
 [ 113.02780914]
 [ 174.60935974]
 [ 164.53981018]
 [ 143.64692688]
 [ 142.6030426 ]
 [ 186.35191345]
 [ 152.77392578]
 [ 151.22254944]
 [ 188.90338135]
 [ 144.17042542]
 [ 181.25106812]
 [ 177.18121338]
 [ 158.42500305]
 [ 176.21305847]
 [ 174.62538147]
 [ 167.44111633]
 [ 150.86540222]
 [ 191.02839661]]
13630 cost:  5.86677 
 hypothesis: 
 [[ 152.63572693]
 [ 185.00798035]
 [ 181.57411194]
 [ 199.23329163]
 [ 139.80456543]
 [ 104.64562988]
 [ 150.21125793]
 [ 113.02886963]
 [ 174.6089325 ]
 [ 164.53962708]
 [ 143.64706421]
 [ 142.60284424]
 [ 186.35177612]
 [ 152.77354431]
 [ 151.2230072 ]
 [ 188.90315247]
 [ 144.16963196]
 [ 181.25202942]
 [ 177.18118286]
 [ 158.42510986]
 [ 176.21354675]
 [ 174.62516785]
 [ 167.44161987]
 [ 150.86540222]
 [ 191.0280304 ]]
13640 cost:  5.8666 
 hypothesis: 
 [[ 152.63606262]
 [ 185.00753784]
 [ 1

14020 cost:  5.86076 
 hypothesis: 
 [[ 152.64900208]
 [ 184.991745  ]
 [ 181.5743103 ]
 [ 199.2386322 ]
 [ 139.77989197]
 [ 104.63145447]
 [ 150.23182678]
 [ 113.06824493]
 [ 174.59248352]
 [ 164.53274536]
 [ 143.65200806]
 [ 142.59544373]
 [ 186.34616089]
 [ 152.75932312]
 [ 151.2394104 ]
 [ 188.89453125]
 [ 144.1398468 ]
 [ 181.28746033]
 [ 177.17997742]
 [ 158.42842102]
 [ 176.23124695]
 [ 174.61695862]
 [ 167.45976257]
 [ 150.86552429]
 [ 191.01383972]]
14030 cost:  5.86063 
 hypothesis: 
 [[ 152.64932251]
 [ 184.99134827]
 [ 181.5743103 ]
 [ 199.23876953]
 [ 139.77928162]
 [ 104.63111877]
 [ 150.23233032]
 [ 113.06921387]
 [ 174.59207153]
 [ 164.53257751]
 [ 143.65213013]
 [ 142.59526062]
 [ 186.34603882]
 [ 152.75900269]
 [ 151.23980713]
 [ 188.89431763]
 [ 144.13912964]
 [ 181.28833008]
 [ 177.17996216]
 [ 158.42849731]
 [ 176.23168945]
 [ 174.61677551]
 [ 167.46020508]
 [ 150.86552429]
 [ 191.01351929]]
14040 cost:  5.86046 
 hypothesis: 
 [[ 152.64964294]
 [ 184.99093628]
 [ 

14430 cost:  5.85556 
 hypothesis: 
 [[ 152.66163635]
 [ 184.97624207]
 [ 181.57449341]
 [ 199.24368286]
 [ 139.75637817]
 [ 104.61791992]
 [ 150.25135803]
 [ 113.10569   ]
 [ 174.57675171]
 [ 164.52610779]
 [ 143.6566925 ]
 [ 142.58833313]
 [ 186.34083557]
 [ 152.74583435]
 [ 151.25497437]
 [ 188.88627625]
 [ 144.11155701]
 [ 181.32115173]
 [ 177.17884827]
 [ 158.43159485]
 [ 176.24809265]
 [ 174.60913086]
 [ 167.47703552]
 [ 150.86567688]
 [ 191.00033569]]
14440 cost:  5.85546 
 hypothesis: 
 [[ 152.66195679]
 [ 184.97590637]
 [ 181.57450867]
 [ 199.24382019]
 [ 139.75584412]
 [ 104.61761475]
 [ 150.25183105]
 [ 113.10655975]
 [ 174.57640076]
 [ 164.5259552 ]
 [ 143.65681458]
 [ 142.58818054]
 [ 186.34072876]
 [ 152.74552917]
 [ 151.25535583]
 [ 188.88609314]
 [ 144.11091614]
 [ 181.32194519]
 [ 177.17884827]
 [ 158.4316864 ]
 [ 176.24848938]
 [ 174.60896301]
 [ 167.47743225]
 [ 150.86569214]
 [ 191.00003052]]
14450 cost:  5.85534 
 hypothesis: 
 [[ 152.66223145]
 [ 184.97555542]
 [ 

14720 cost:  5.85248 
 hypothesis: 
 [[ 152.66989136]
 [ 184.96626282]
 [ 181.57467651]
 [ 199.24700928]
 [ 139.74118042]
 [ 104.60914612]
 [ 150.2640686 ]
 [ 113.12995911]
 [ 174.56660461]
 [ 164.52182007]
 [ 143.65975952]
 [ 142.58375549]
 [ 186.33743286]
 [ 152.73712158]
 [ 151.2651062 ]
 [ 188.88098145]
 [ 144.09326172]
 [ 181.34303284]
 [ 177.17817688]
 [ 158.43370056]
 [ 176.25901794]
 [ 174.6040802 ]
 [ 167.48825073]
 [ 150.86584473]
 [ 190.99162292]]
14730 cost:  5.85239 
 hypothesis: 
 [[ 152.67015076]
 [ 184.96592712]
 [ 181.57466125]
 [ 199.24711609]
 [ 139.74066162]
 [ 104.60886383]
 [ 150.26448059]
 [ 113.13076019]
 [ 174.56626892]
 [ 164.52166748]
 [ 143.65983582]
 [ 142.58360291]
 [ 186.33732605]
 [ 152.73683167]
 [ 151.26542664]
 [ 188.88078308]
 [ 144.09265137]
 [ 181.34375   ]
 [ 177.17814636]
 [ 158.4337616 ]
 [ 176.25938416]
 [ 174.60391235]
 [ 167.48860168]
 [ 150.86582947]
 [ 190.99133301]]
14740 cost:  5.85229 
 hypothesis: 
 [[ 152.67042542]
 [ 184.96559143]
 [ 

15120 cost:  5.8489 
 hypothesis: 
 [[ 152.68029785]
 [ 184.9535675 ]
 [ 181.57484436]
 [ 199.25119019]
 [ 139.72190857]
 [ 104.5980072 ]
 [ 150.28007507]
 [ 113.16064453]
 [ 174.55369568]
 [ 164.51631165]
 [ 143.66358948]
 [ 142.57791138]
 [ 186.33311462]
 [ 152.72608948]
 [ 151.27786255]
 [ 188.87420654]
 [ 144.07008362]
 [ 181.37068176]
 [ 177.17729187]
 [ 158.43632507]
 [ 176.27282715]
 [ 174.59765625]
 [ 167.50239563]
 [ 150.86601257]
 [ 190.98057556]]
15130 cost:  5.84883 
 hypothesis: 
 [[ 152.68054199]
 [ 184.95326233]
 [ 181.57485962]
 [ 199.251297  ]
 [ 139.72142029]
 [ 104.59774017]
 [ 150.28045654]
 [ 113.16136169]
 [ 174.5533905 ]
 [ 164.51618958]
 [ 143.66368103]
 [ 142.57777405]
 [ 186.33299255]
 [ 152.72583008]
 [ 151.27815247]
 [ 188.8740387 ]
 [ 144.0695343 ]
 [ 181.37132263]
 [ 177.17727661]
 [ 158.43638611]
 [ 176.27314758]
 [ 174.5974884 ]
 [ 167.50273132]
 [ 150.86601257]
 [ 190.9803009 ]]
15140 cost:  5.84873 
 hypothesis: 
 [[ 152.68078613]
 [ 184.95295715]
 [ 1

15550 cost:  5.84576 
 hypothesis: 
 [[ 152.69039917]
 [ 184.94126892]
 [ 181.57504272]
 [ 199.25523376]
 [ 139.70320129]
 [ 104.58717346]
 [ 150.29560852]
 [ 113.19035339]
 [ 174.54115295]
 [ 164.51092529]
 [ 143.66729736]
 [ 142.57221985]
 [ 186.32893372]
 [ 152.71543884]
 [ 151.29020691]
 [ 188.86764526]
 [ 144.0476532 ]
 [ 181.39746094]
 [ 177.1764679 ]
 [ 158.43891907]
 [ 176.28619385]
 [ 174.59138489]
 [ 167.51612854]
 [ 150.8662262 ]
 [ 190.96986389]]
15560 cost:  5.8457 
 hypothesis: 
 [[ 152.69061279]
 [ 184.94099426]
 [ 181.57504272]
 [ 199.25531006]
 [ 139.70278931]
 [ 104.58693695]
 [ 150.29592896]
 [ 113.19100952]
 [ 174.54089355]
 [ 164.51080322]
 [ 143.66737366]
 [ 142.57208252]
 [ 186.32885742]
 [ 152.71517944]
 [ 151.29046631]
 [ 188.86749268]
 [ 144.04714966]
 [ 181.39804077]
 [ 177.17645264]
 [ 158.43896484]
 [ 176.28649902]
 [ 174.59124756]
 [ 167.51641846]
 [ 150.86624146]
 [ 190.96963501]]
15570 cost:  5.84563 
 hypothesis: 
 [[ 152.69082642]
 [ 184.9407196 ]
 [ 1

15960 cost:  5.84334 
 hypothesis: 
 [[ 152.69906616]
 [ 184.93067932]
 [ 181.57519531]
 [ 199.25868225]
 [ 139.68711853]
 [ 104.57782745]
 [ 150.30889893]
 [ 113.21582794]
 [ 174.53036499]
 [ 164.5062561 ]
 [ 143.67045593]
 [ 142.567276  ]
 [ 186.3253479 ]
 [ 152.70626831]
 [ 151.30078125]
 [ 188.86196899]
 [ 144.02839661]
 [ 181.42044067]
 [ 177.17576599]
 [ 158.44111633]
 [ 176.29763794]
 [ 174.58599854]
 [ 167.52786255]
 [ 150.86642456]
 [ 190.96064758]]
15970 cost:  5.84328 
 hypothesis: 
 [[ 152.69926453]
 [ 184.93043518]
 [ 181.57519531]
 [ 199.2587738 ]
 [ 139.68675232]
 [ 104.57762146]
 [ 150.3092041 ]
 [ 113.21641541]
 [ 174.53010559]
 [ 164.50614929]
 [ 143.67051697]
 [ 142.56716919]
 [ 186.32527161]
 [ 152.70605469]
 [ 151.30104065]
 [ 188.86184692]
 [ 144.02796936]
 [ 181.42097473]
 [ 177.17576599]
 [ 158.44117737]
 [ 176.29792786]
 [ 174.58589172]
 [ 167.52815247]
 [ 150.86643982]
 [ 190.96043396]]
15980 cost:  5.84324 
 hypothesis: 
 [[ 152.69947815]
 [ 184.93019104]
 [ 

16370 cost:  5.84136 
 hypothesis: 
 [[ 152.70690918]
 [ 184.92114258]
 [ 181.57536316]
 [ 199.26185608]
 [ 139.67260742]
 [ 104.5694046 ]
 [ 150.32092285]
 [ 113.2388382 ]
 [ 174.52062988]
 [ 164.50204468]
 [ 143.67330933]
 [ 142.56283569]
 [ 186.32217407]
 [ 152.69802856]
 [ 151.31034851]
 [ 188.85688782]
 [ 144.01104736]
 [ 181.44119263]
 [ 177.1751709 ]
 [ 158.44316101]
 [ 176.30801392]
 [ 174.5811615 ]
 [ 167.53851318]
 [ 150.86665344]
 [ 190.95236206]]
16380 cost:  5.84131 
 hypothesis: 
 [[ 152.7071228 ]
 [ 184.92095947]
 [ 181.57537842]
 [ 199.26194763]
 [ 139.67230225]
 [ 104.56921387]
 [ 150.32119751]
 [ 113.23937225]
 [ 174.52041626]
 [ 164.50195312]
 [ 143.67340088]
 [ 142.56274414]
 [ 186.32211304]
 [ 152.69786072]
 [ 151.31057739]
 [ 188.85678101]
 [ 144.01065063]
 [ 181.44171143]
 [ 177.1751709 ]
 [ 158.44320679]
 [ 176.30827332]
 [ 174.58105469]
 [ 167.53877258]
 [ 150.8666687 ]
 [ 190.95217896]]
16390 cost:  5.84127 
 hypothesis: 
 [[ 152.70729065]
 [ 184.92071533]
 [ 

16790 cost:  5.8397 
 hypothesis: 
 [[ 152.71418762]
 [ 184.91235352]
 [ 181.57551575]
 [ 199.26478577]
 [ 139.65922546]
 [ 104.5615921 ]
 [ 150.33201599]
 [ 113.2600708 ]
 [ 174.51164246]
 [ 164.49815369]
 [ 143.67597961]
 [ 142.55873108]
 [ 186.31922913]
 [ 152.69044495]
 [ 151.31919861]
 [ 188.85220337]
 [ 143.99502563]
 [ 181.46038818]
 [ 177.17462158]
 [ 158.44503784]
 [ 176.31759644]
 [ 174.57669067]
 [ 167.5483551 ]
 [ 150.86686707]
 [ 190.94471741]]
16800 cost:  5.83967 
 hypothesis: 
 [[ 152.71434021]
 [ 184.91217041]
 [ 181.57553101]
 [ 199.26486206]
 [ 139.65892029]
 [ 104.56141663]
 [ 150.33227539]
 [ 113.26055908]
 [ 174.51144409]
 [ 164.49806213]
 [ 143.67602539]
 [ 142.55865479]
 [ 186.31915283]
 [ 152.69026184]
 [ 151.31938171]
 [ 188.85209656]
 [ 143.99465942]
 [ 181.46081543]
 [ 177.17462158]
 [ 158.44506836]
 [ 176.31781006]
 [ 174.57658386]
 [ 167.54855347]
 [ 150.86685181]
 [ 190.94454956]]
16810 cost:  5.83963 
 hypothesis: 
 [[ 152.71450806]
 [ 184.91197205]
 [ 1

 [ 190.93798828]]
17210 cost:  5.83836 
 hypothesis: 
 [[ 152.72071838]
 [ 184.90441895]
 [ 181.57566833]
 [ 199.26741028]
 [ 139.6471405 ]
 [ 104.55453491]
 [ 150.34199524]
 [ 113.27915955]
 [ 174.50352478]
 [ 164.49458313]
 [ 143.67832947]
 [ 142.55500793]
 [ 186.3165741 ]
 [ 152.68360901]
 [ 151.32711792]
 [ 188.84794617]
 [ 143.98060608]
 [ 181.47764587]
 [ 177.17414856]
 [ 158.44673157]
 [ 176.32621765]
 [ 174.57261658]
 [ 167.55717468]
 [ 150.86708069]
 [ 190.93783569]]
17220 cost:  5.83832 
 hypothesis: 
 [[ 152.72087097]
 [ 184.9042511 ]
 [ 181.57569885]
 [ 199.26747131]
 [ 139.6468811 ]
 [ 104.55437469]
 [ 150.34223938]
 [ 113.27959442]
 [ 174.50334167]
 [ 164.49450684]
 [ 143.6783905 ]
 [ 142.55493164]
 [ 186.31654358]
 [ 152.68345642]
 [ 151.32730103]
 [ 188.84786987]
 [ 143.9803009 ]
 [ 181.4780426 ]
 [ 177.17414856]
 [ 158.4467926 ]
 [ 176.32641602]
 [ 174.57255554]
 [ 167.55738831]
 [ 150.86708069]
 [ 190.93768311]]
17230 cost:  5.8383 
 hypothesis: 
 [[ 152.7210083 ]
 [ 

17610 cost:  5.8373 
 hypothesis: 
 [[ 152.72631836]
 [ 184.89761353]
 [ 181.57579041]
 [ 199.26968384]
 [ 139.63674927]
 [ 104.54846191]
 [ 150.35058594]
 [ 113.29558563]
 [ 174.49653625]
 [ 164.49154663]
 [ 143.68035889]
 [ 142.55180359]
 [ 186.31430054]
 [ 152.67770386]
 [ 151.33392334]
 [ 188.84429932]
 [ 143.96818542]
 [ 181.49249268]
 [ 177.17370605]
 [ 158.44818115]
 [ 176.33361816]
 [ 174.56915283]
 [ 167.56478882]
 [ 150.86721802]
 [ 190.93191528]]
17620 cost:  5.83729 
 hypothesis: 
 [[ 152.72647095]
 [ 184.89744568]
 [ 181.57580566]
 [ 199.26972961]
 [ 139.63650513]
 [ 104.54830933]
 [ 150.35079956]
 [ 113.2959671 ]
 [ 174.49636841]
 [ 164.49147034]
 [ 143.68041992]
 [ 142.55172729]
 [ 186.31425476]
 [ 152.67758179]
 [ 151.33410645]
 [ 188.84420776]
 [ 143.96789551]
 [ 181.49284363]
 [ 177.17370605]
 [ 158.44822693]
 [ 176.33380127]
 [ 174.56906128]
 [ 167.56497192]
 [ 150.86724854]
 [ 190.9317627 ]]
17630 cost:  5.83725 
 hypothesis: 
 [[ 152.72659302]
 [ 184.89727783]
 [ 1

18000 cost:  5.83646 
 hypothesis: 
 [[ 152.73130798]
 [ 184.8915863 ]
 [ 181.57591248]
 [ 199.27168274]
 [ 139.62756348]
 [ 104.5430603 ]
 [ 150.35813904]
 [ 113.31005096]
 [ 174.49035645]
 [ 164.48880005]
 [ 143.68214417]
 [ 142.5489502 ]
 [ 186.31231689]
 [ 152.67253113]
 [ 151.3399353 ]
 [ 188.84107971]
 [ 143.95726013]
 [ 181.50559998]
 [ 177.17338562]
 [ 158.44949341]
 [ 176.34014893]
 [ 174.5660553 ]
 [ 167.57148743]
 [ 150.86741638]
 [ 190.92668152]]
18010 cost:  5.83645 
 hypothesis: 
 [[ 152.73143005]
 [ 184.89144897]
 [ 181.57594299]
 [ 199.27174377]
 [ 139.62734985]
 [ 104.54293823]
 [ 150.35835266]
 [ 113.3104248 ]
 [ 174.49021912]
 [ 164.48875427]
 [ 143.68222046]
 [ 142.54890442]
 [ 186.31228638]
 [ 152.67242432]
 [ 151.34010315]
 [ 188.84101868]
 [ 143.95698547]
 [ 181.50593567]
 [ 177.17338562]
 [ 158.44953918]
 [ 176.34031677]
 [ 174.56599426]
 [ 167.57167053]
 [ 150.86743164]
 [ 190.92657471]]
18020 cost:  5.8364 
 hypothesis: 
 [[ 152.73153687]
 [ 184.89129639]
 [ 1

18420 cost:  5.83571 
 hypothesis: 
 [[ 152.73612976]
 [ 184.88574219]
 [ 181.57606506]
 [ 199.2736969 ]
 [ 139.61860657]
 [ 104.53777313]
 [ 150.36552429]
 [ 113.32413483]
 [ 174.48435974]
 [ 164.48616028]
 [ 143.68388367]
 [ 142.5461731 ]
 [ 186.31040955]
 [ 152.66749573]
 [ 151.34580994]
 [ 188.83796692]
 [ 143.94659424]
 [ 181.5184021 ]
 [ 177.17304993]
 [ 158.45075989]
 [ 176.34654236]
 [ 174.56307983]
 [ 167.57804871]
 [ 150.86758423]
 [ 190.92164612]]
18430 cost:  5.8357 
 hypothesis: 
 [[ 152.73625183]
 [ 184.88560486]
 [ 181.57606506]
 [ 199.27371216]
 [ 139.6184082 ]
 [ 104.5376358 ]
 [ 150.36567688]
 [ 113.32443237]
 [ 174.48420715]
 [ 164.48609924]
 [ 143.68392944]
 [ 142.5460968 ]
 [ 186.31034851]
 [ 152.66737366]
 [ 151.34593201]
 [ 188.83787537]
 [ 143.94633484]
 [ 181.51867676]
 [ 177.17304993]
 [ 158.45079041]
 [ 176.34666443]
 [ 174.56300354]
 [ 167.57817078]
 [ 150.86756897]
 [ 190.92152405]]
18440 cost:  5.83567 
 hypothesis: 
 [[ 152.73635864]
 [ 184.88546753]
 [ 1

18830 cost:  5.83509 
 hypothesis: 
 [[ 152.74038696]
 [ 184.88059998]
 [ 181.57617188]
 [ 199.27542114]
 [ 139.61073303]
 [ 104.53308868]
 [ 150.37199402]
 [ 113.33647156]
 [ 174.4790802 ]
 [ 164.48382568]
 [ 143.68540955]
 [ 142.54371643]
 [ 186.30871582]
 [ 152.66305542]
 [ 151.35093689]
 [ 188.8352356 ]
 [ 143.93719482]
 [ 181.52963257]
 [ 177.17276001]
 [ 158.45187378]
 [ 176.35214233]
 [ 174.56045532]
 [ 167.58380127]
 [ 150.8677063 ]
 [ 190.91719055]]
18840 cost:  5.83509 
 hypothesis: 
 [[ 152.74049377]
 [ 184.88047791]
 [ 181.57618713]
 [ 199.27546692]
 [ 139.61054993]
 [ 104.53297424]
 [ 150.37214661]
 [ 113.33676147]
 [ 174.47895813]
 [ 164.48376465]
 [ 143.68544006]
 [ 142.5436554 ]
 [ 186.3086853 ]
 [ 152.66294861]
 [ 151.35105896]
 [ 188.8351593 ]
 [ 143.9369812 ]
 [ 181.52989197]
 [ 177.17276001]
 [ 158.45188904]
 [ 176.35227966]
 [ 174.56039429]
 [ 167.58392334]
 [ 150.86772156]
 [ 190.91708374]]
18850 cost:  5.83507 
 hypothesis: 
 [[ 152.74057007]
 [ 184.88035583]
 [ 

19260 cost:  5.83457 
 hypothesis: 
 [[ 152.74440002]
 [ 184.87574768]
 [ 181.5763092 ]
 [ 199.27708435]
 [ 139.60327148]
 [ 104.52865601]
 [ 150.37809753]
 [ 113.34812164]
 [ 174.47407532]
 [ 164.48158264]
 [ 143.68682861]
 [ 142.54136658]
 [ 186.30714417]
 [ 152.65885925]
 [ 151.35577393]
 [ 188.8326416 ]
 [ 143.92835999]
 [ 181.54025269]
 [ 177.17251587]
 [ 158.45292664]
 [ 176.35743713]
 [ 174.55795288]
 [ 167.58921814]
 [ 150.86787415]
 [ 190.91299438]]
19270 cost:  5.83457 
 hypothesis: 
 [[ 152.74449158]
 [ 184.87564087]
 [ 181.57629395]
 [ 199.27713013]
 [ 139.60310364]
 [ 104.52854156]
 [ 150.37823486]
 [ 113.34837341]
 [ 174.47395325]
 [ 164.48153687]
 [ 143.68685913]
 [ 142.54130554]
 [ 186.30711365]
 [ 152.6587677 ]
 [ 151.35586548]
 [ 188.83258057]
 [ 143.92814636]
 [ 181.54048157]
 [ 177.17251587]
 [ 158.45294189]
 [ 176.35754395]
 [ 174.55789185]
 [ 167.58932495]
 [ 150.86787415]
 [ 190.91290283]]
19280 cost:  5.83456 
 hypothesis: 
 [[ 152.74459839]
 [ 184.87554932]
 [ 

19660 cost:  5.83417 
 hypothesis: 
 [[ 152.74777222]
 [ 184.87167358]
 [ 181.57640076]
 [ 199.27848816]
 [ 139.59701538]
 [ 104.52490234]
 [ 150.38320923]
 [ 113.35787964]
 [ 174.46986389]
 [ 164.47970581]
 [ 143.68800354]
 [ 142.53939819]
 [ 186.30584717]
 [ 152.65534973]
 [ 151.35983276]
 [ 188.83045959]
 [ 143.9209137 ]
 [ 181.54916382]
 [ 177.17230225]
 [ 158.4538269 ]
 [ 176.36187744]
 [ 174.55587769]
 [ 167.59378052]
 [ 150.86801147]
 [ 190.90948486]]
19670 cost:  5.83416 
 hypothesis: 
 [[ 152.74784851]
 [ 184.87158203]
 [ 181.57640076]
 [ 199.27851868]
 [ 139.59684753]
 [ 104.52481079]
 [ 150.38331604]
 [ 113.35810089]
 [ 174.46977234]
 [ 164.47964478]
 [ 143.68803406]
 [ 142.53935242]
 [ 186.30580139]
 [ 152.65527344]
 [ 151.35992432]
 [ 188.83039856]
 [ 143.92074585]
 [ 181.54936218]
 [ 177.17230225]
 [ 158.45384216]
 [ 176.36198425]
 [ 174.55581665]
 [ 167.59388733]
 [ 150.86799622]
 [ 190.90940857]]
19680 cost:  5.83415 
 hypothesis: 
 [[ 152.74794006]
 [ 184.87149048]
 [ 

In [23]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, 
           feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis, 
           feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Your score will be  [[ 186.99308777]]
Other scores will be  [[ 182.69264221]
 [ 175.29800415]]
