In [1]:
import tensorflow as tf

In [2]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'],shuffle=False,name = 'filename_queue')

In [3]:
reader = tf.TextLineReader()
key,value = reader.read(filename_queue)

In [4]:
# Default values, in case of empty column,Also specifies the type of the decode result
record_defaults = [[0.], [0.], [0.], [0.]]# 在这里其实我们是知道这里面有四列
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [5]:
# collect batches of csv in
train_x_batch,train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]],
                                             batch_size = 10)
# 一个取三列 一个取一列

In [6]:
# placeholder for a tensor that will always fed
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [7]:
# Hypothesis
hypothesis = tf.matmul(X,W)+b


In [8]:
# simplified cost/loss Function
cost = tf.reduce_mean(tf.square(hypothesis - Y))


In [9]:
# Minilize the cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-6)
train = optimizer.minimize(cost)


In [10]:
# launch the graph in a session
sess = tf.Session()
# initializes global variable in the graph
sess.run(tf.global_variables_initializer())


In [11]:
# start the populating the filename queue
coord = tf.train.Coordinator()#对进程进行协调
threads = tf.train.start_queue_runners(sess = sess,coord=coord)

In [12]:
for step in range(2001):
   x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
   cost_val, hy_val, _ = sess.run(
       [cost, hypothesis, train], 
       feed_dict={X: x_batch, Y: y_batch})
   if step % 10 == 0:
       print(step, "Cost: ", cost_val, 
                   "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)


0 Cost:  115720.0 
Prediction:
 [[-180.43357849]
 [-215.00770569]
 [-213.09579468]
 [-229.25979614]
 [-165.71560669]
 [-117.35925293]
 [-167.74458313]
 [-119.06659698]
 [-196.93515015]
 [-175.84352112]]
10 Cost:  51745.6 
Prediction:
 [[-70.94221497]
 [-83.40851593]
 [-83.42929077]
 [-88.04357147]
 [-65.34924316]
 [-43.36384964]
 [-62.0401535 ]
 [-40.70497894]
 [-73.94671631]
 [-61.92723846]]
20 Cost:  23083.3 
Prediction:
 [[  2.45735335]
 [  4.8110981 ]
 [  3.49492049]
 [  6.62297249]
 [  1.93302321]
 [  6.23985863]
 [  8.82029915]
 [ 11.82556725]
 [  8.50020027]
 [ 14.43754768]]
30 Cost:  10261.3 
Prediction:
 [[ 51.66220474]
 [ 63.9505043 ]
 [ 61.76613235]
 [ 70.084198  ]
 [ 47.0368309 ]
 [ 39.49219131]
 [ 56.32252121]
 [ 47.03983307]
 [ 63.7694664 ]
 [ 65.62910461]]
40 Cost:  4538.35 
Prediction:
 [[  84.6477356 ]
 [ 103.59551239]
 [ 100.82933807]
 [ 112.62643433]
 [  77.27294922]
 [  61.78310776]
 [  88.16617584]
 [  70.64582825]
 [ 100.81973267]
 [  99.94537354]]
50 Cost:  1992.

470 Cost:  11.9101 
Prediction:
 [[ 151.76167297]
 [ 184.21592712]
 [ 180.29096985]
 [ 199.13993835]
 [ 138.76972961]
 [ 107.07647705]
 [ 152.897995  ]
 [ 118.59819794]
 [ 176.12290955]
 [ 169.63246155]]
480 Cost:  11.9043 
Prediction:
 [[ 151.76245117]
 [ 184.21582031]
 [ 180.29144287]
 [ 199.13987732]
 [ 138.7698822 ]
 [ 107.07554626]
 [ 152.89730835]
 [ 118.59689331]
 [ 176.12181091]
 [ 169.63000488]]
490 Cost:  11.8985 
Prediction:
 [[ 151.76322937]
 [ 184.21569824]
 [ 180.29191589]
 [ 199.13977051]
 [ 138.77003479]
 [ 107.07459259]
 [ 152.89663696]
 [ 118.5955658 ]
 [ 176.12071228]
 [ 169.62756348]]
500 Cost:  11.8928 
Prediction:
 [[ 151.76400757]
 [ 184.21559143]
 [ 180.29238892]
 [ 199.13970947]
 [ 138.77020264]
 [ 107.07364655]
 [ 152.89596558]
 [ 118.59423828]
 [ 176.11964417]
 [ 169.62513733]]
510 Cost:  11.8871 
Prediction:
 [[ 151.76478577]
 [ 184.21549988]
 [ 180.29289246]
 [ 199.13963318]
 [ 138.77035522]
 [ 107.07270813]
 [ 152.89529419]
 [ 118.5929184 ]
 [ 176.11856079

970 Cost:  11.6281 
Prediction:
 [[ 151.80015564]
 [ 184.21073914]
 [ 180.31483459]
 [ 199.13594055]
 [ 138.77774048]
 [ 107.02998352]
 [ 152.86471558]
 [ 118.53274536]
 [ 176.06941223]
 [ 169.51190186]]
980 Cost:  11.6226 
Prediction:
 [[ 151.80093384]
 [ 184.21066284]
 [ 180.31532288]
 [ 199.13587952]
 [ 138.77790833]
 [ 107.02907562]
 [ 152.86405945]
 [ 118.53145599]
 [ 176.06835938]
 [ 169.50952148]]
990 Cost:  11.617 
Prediction:
 [[ 151.80168152]
 [ 184.21055603]
 [ 180.3157959 ]
 [ 199.13578796]
 [ 138.77806091]
 [ 107.02815247]
 [ 152.86338806]
 [ 118.53015137]
 [ 176.06730652]
 [ 169.50714111]]
1000 Cost:  11.6116 
Prediction:
 [[ 151.80245972]
 [ 184.21046448]
 [ 180.31626892]
 [ 199.13572693]
 [ 138.77824402]
 [ 107.02724457]
 [ 152.86274719]
 [ 118.52886963]
 [ 176.06626892]
 [ 169.504776  ]]
1010 Cost:  11.606 
Prediction:
 [[ 151.80319214]
 [ 184.21035767]
 [ 180.31674194]
 [ 199.13562012]
 [ 138.77838135]
 [ 107.02632141]
 [ 152.86207581]
 [ 118.527565  ]
 [ 176.06520081

1480 Cost:  11.3519 
Prediction:
 [[ 151.83842468]
 [ 184.20576477]
 [ 180.33866882]
 [ 199.13189697]
 [ 138.78598022]
 [ 106.98376465]
 [ 152.83132935]
 [ 118.46707916]
 [ 176.01623535]
 [ 169.39175415]]
1490 Cost:  11.3466 
Prediction:
 [[ 151.8391571 ]
 [ 184.20567322]
 [ 180.33912659]
 [ 199.13182068]
 [ 138.78614807]
 [ 106.98287201]
 [ 152.83067322]
 [ 118.46581268]
 [ 176.01521301]
 [ 169.38941956]]
1500 Cost:  11.3413 
Prediction:
 [[ 151.83990479]
 [ 184.20559692]
 [ 180.33959961]
 [ 199.13174438]
 [ 138.78631592]
 [ 106.98197174]
 [ 152.83003235]
 [ 118.46453094]
 [ 176.01419067]
 [ 169.38710022]]
1510 Cost:  11.336 
Prediction:
 [[ 151.84063721]
 [ 184.20547485]
 [ 180.34005737]
 [ 199.13165283]
 [ 138.78645325]
 [ 106.9810791 ]
 [ 152.82937622]
 [ 118.46325684]
 [ 176.01315308]
 [ 169.38475037]]
1520 Cost:  11.3307 
Prediction:
 [[ 151.84138489]
 [ 184.20539856]
 [ 180.3405304 ]
 [ 199.1315918 ]
 [ 138.78663635]
 [ 106.98019409]
 [ 152.82873535]
 [ 118.46198273]
 [ 176.0121

1880 Cost:  11.1431 
Prediction:
 [[ 151.86773682]
 [ 184.20205688]
 [ 180.35699463]
 [ 199.12876892]
 [ 138.79249573]
 [ 106.948349  ]
 [ 152.80554199]
 [ 118.41635132]
 [ 175.97550964]
 [ 169.29946899]]
1890 Cost:  11.138 
Prediction:
 [[ 151.86845398]
 [ 184.20195007]
 [ 180.35743713]
 [ 199.12867737]
 [ 138.79264832]
 [ 106.94746399]
 [ 152.80488586]
 [ 118.41508484]
 [ 175.9744873 ]
 [ 169.29718018]]
1900 Cost:  11.1329 
Prediction:
 [[ 151.86920166]
 [ 184.20188904]
 [ 180.35791016]
 [ 199.12861633]
 [ 138.79283142]
 [ 106.94658661]
 [ 152.80426025]
 [ 118.41383362]
 [ 175.97351074]
 [ 169.29490662]]
1910 Cost:  11.1277 
Prediction:
 [[ 151.86990356]
 [ 184.20178223]
 [ 180.3583374 ]
 [ 199.12852478]
 [ 138.79298401]
 [ 106.94571686]
 [ 152.80361938]
 [ 118.41257477]
 [ 175.97247314]
 [ 169.2926178 ]]
1920 Cost:  11.1226 
Prediction:
 [[ 151.87062073]
 [ 184.20169067]
 [ 180.35879517]
 [ 199.12844849]
 [ 138.7931366 ]
 [ 106.94483185]
 [ 152.80296326]
 [ 118.41130066]
 [ 175.9714